### ISSUE TITLE
Wrong conversion to pixels from points

### ISSUE THREAD

**Issue by omerts** [bezoerb/text-metrics#13]
Hey,

Thanks for the lib, really helpful. 
Seems like there is a small bug with the conversion from pts to inch.
Current implementation:
```
return value / (96 / 72);
```
Should be:
```
return value * (96 / 72);
```

**Comment by omerts** [comment]
Created https://github.com/bezoerb/text-metrics/pull/14

**Comment by bezoerb** [comment]
Good catch 😊
PR is merged. Thanks @omerts
