### ISSUE TITLE
latest version is missing the dist folder

### ISSUE THREAD

**Issue by yocontra** [bezoerb/text-metrics#18]
https://github.com/bezoerb/text-metrics/releases/tag/v2.0.4

Package is invalid because the dist folder is missing. 2.0.3 works fine, so seems to be introduced with the CI changes.

**Comment by bezoerb** [comment]
Thanks @contra :)
Needed a few tries to find the error but it's now fixed in [v2.0.7](https://github.com/bezoerb/text-metrics/releases/tag/v2.0.7)
