### ISSUE TITLE
TypeScript definitions?

### ISSUE THREAD

**Issue by jhurliman** [bezoerb/text-metrics#19]

**Comment by jose-adalo** [comment]
I would also like typescript definitions, I'm writing my own for my project

**Comment by modus-jose** [comment]
I am adding typescript definitions. 
I'm working on it here:
https://github.com/theresasogunle/react-ts-text-metrics

**Comment by modus-jose** [comment]
@theresasogunle and I are working on a contribution to typescript.
We used this repo to test, 
https://github.com/theresasogunle/react-ts-text-metrics

and are making this fork
https://github.com/modus-jose/DefinitelyTyped

Can someone help us test our definitions??

**Comment by bezoerb** [comment]
hey @modus-jose :)
there's a plan to rewrite this module to typescript but i'm quite busy at the moment.

**Comment by modus-jose** [comment]
Hey Ben,

I would be happy to contribute rewriting it n typescript if you don't have
the time.

We started with definitioms as that seemed simpler and we had already added
them yo one of our projects

And btw thanks for the small library, it's awesome!!

**Comment by bezoerb** [comment]
Hey @modus-jose, that would be awesome 😄

**Comment by modus-jose** [comment]
And its been merged!
You can now add 
npm i --save-dev @types/text-metrics
