### ISSUE TITLE
You are not exporting anything

### ISSUE THREAD

**Issue by linonetwo** [bezoerb/text-metrics#5]
```js
import textMetrics from 'text-metrics';

console.log('textMetrics', textMetrics);
```

logs undefined.

**Comment by bezoerb** [comment]
@linonetwo: Thanks for the info, i'll take a loom in the next days :)

**Comment by jay-jlm** [comment]
@linonetwo  the syntax you used for default exports.

To access named exports in JS you can use the following sintaxes:
`import * as someConst from 'text-metrics';`

or :

`import { init, utils } from 'text-metrics';`

More info about  more about this topic is available here:
https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export

**Comment by linonetwo** [comment]
OK, thanks. Maybe @bezoerb  can add this to the Readme?
